version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    target-branch: dependabot/bumps
    schedule:
      interval: weekly
      day: tuesday
      timezone: US/Eastern
      time: '06:00'
    open-pull-requests-limit: 99
